version: '3'
services:
  db:
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: doho
      MYSQL_USER: doho
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
  web:
    image: LMS:latest
    ports:
      - 8080:8080